server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: interview-service
          uri: lb://interview-service
          predicates:
            - Path=/interview/**
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
        - id: candidate-service
          uri: lb://candidate-service
          predicates:
            - Path=/candidate/**
        - id: panelist-service
          uri: lb://panelist-service
          predicates:
            - Path=/panelist/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/feedback/**
        - id: camera-service
          uri: lb://camera-service
          predicates:
            - Path=/cameratest/**
        - id: camera-service
          uri: lb://camera-service
          predicates:
            - Path=/camera/**
